server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

management.endpoint.health.show-details=always

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html




